#ifndef SPI_CONFIG_H
#define	SPI_CONFIG_H

//#define SPI_CHANNEL1_FORCE_DISABLE
//#define SPI_CHANNEL2_FORCE_DISABLE

#define SPI_RX_INTERRUPT_PRIORITY       INTERRUPT_PRIORITY_1
#define SPI_TX_INTERRUPT_PRIORITY       INTERRUPT_PRIORITY_1
#define SPI_FAULT_INTERRUPT_PRIORITY    INTERRUPT_PRIORITY_1

#endif	/* SPI_CONFIG_H */

