#ifndef UART_CONFIG_H
#define	UART_CONFIG_H

//#define UART_CHANNEL1_FORCE_DISABLE
//#define UART_CHANNEL2_FORCE_DISABLE
#define UART_CHANNEL3_FORCE_DISABLE
#define UART_CHANNEL4_FORCE_DISABLE
#define UART_CHANNEL5_FORCE_DISABLE
#define UART_CHANNEL6_FORCE_DISABLE

#define UART_RX_INTERRUPT_PRIORITY      INTERRUPT_PRIORITY_1
#define UART_TX_INTERRUPT_PRIORITY      INTERRUPT_PRIORITY_1
#define UART_FAULT_INTERRUPT_PRIORITY   INTERRUPT_PRIORITY_1

#define UART_STREAM_ENABLE
#define UART_STREAM_CHANNEL             UART_CHANNEL2
#define UART_STREAM_BAUDRATE            115200

#endif	/* UART_CONFIG_H */

